{
    width : 48, height : 48, bpp : 3,
    transparent : 2,
    buffer : require("heatshrink").decompress(atob("pMkyVAgESAoQCCpAOEAQOQgEEBwYCDkEAhIIDwEBBwoLJC4oCBgAvEFIgFDBAZNDIIYQBgeACIsCMohfDj/0NYoRDBoMSCIM///wBYZWCgBBCgECoEECISGFwmQMYIVBKwW/CI+kNggRCyH///AQAgDBAwIRCSQMAjYRIEYgRCEYPQCJZMC/+f/AROgeBCIJ3CghZDNYQWDuPAMIQSCCIPgAwSnDh0HCIjqC3ARGgARGYAKtBGwI6Dh/4CIsCpEH//+CIQJBCI4sCVoQRDr5ZFCIZHEEYQRNRIQRJn4RQEaIADCKQDCCKSPICK5fBh//CJdICIUBCKXgCJinBb4P8CJUICIQjB//wCJZZDAAJuJgJ9DCISkJCIUcGoQjKgEgK4PxCJpZB/+NCIXHQBFAggRBx4QBEwIRHgSPBw4hC/hcB8eACJCPBv5HDgYRGiTpCB4R9Cj4RBjgRDyVJkEACAeB4H/xwiEggRBkkAj/+LgOAn41CBAIRBkgRCH4Q4BAgTdEgIRDyQRF8ZxCBIMJCIlACIQdB8F/WwUCBwQ="))
  }